---
title: "week_8_assignment"
author: "Anne Dobberteen"
date: "3/18/2019"
output: html_document
---

```{r}
library(tidyverse)
manufacturing <- read_csv("nhgis0001_csv/nhgis0001_ds20_1870_state.csv")
```
```{r}
## This is a NHGIS data set taken from the 1870 Census, specifically the manufacturing data portion of the census. The dataset is described by the NHGIS as a table that shows the horsepower generated by other types of power (steam and water) that was used in manufacturing. It is organized by state. Although county information is available in a separate table, for this assignment I am choosing to focus on the state table for simplicity's sake. 

## Through my explortory data analysis, I hope to eventually be able to answer the following quesions: Which states generated the most power from water for manufacturing in 1870? Which states generated the most power from steam for manufacturing in 1870? What state produced the most power for manufacturing, total? 
```

```{r}
#How many rows and columnns are in the data set? What does this tell you about the data?
nrow(manufacturing)

ncol(manufacturing)
```
```{r}
#There are 47 rows and 8 columns. Each row represents a state, but some of them are actually territories, not yet states (such as Arizona Territory, Colorado Territory, etc.) The District of Columbia is counted as a state, even though it isn't one. Instead of being counted as two states or territories, North and South Dakota are counted together, as "Dakota Territory." Hawaii and Alaska are not included. This explains why there are 47 rows.
```

```{r}
#Now run str() and see if you notice anyting odd about the data.
str(manufacturing)
#This looks generally okay to me. 
```
```{r}
#The last two column names are confusing, so I will change them so that it is easy to see what they mean.


colnames(manufacturing)[colnames(manufacturing)=="AN4001"] <- "water_wheel"
str(manufacturing)

colnames(manufacturing)[colnames(manufacturing)=="AN4002"] <- "steam_engine"
str(manufacturing)
```

```{r}
#Look at the top and bottom of the data. Does it all look like it should? 

head(manufacturing[, c(2, 3, 7, 8)])
tail(manufacturing[, c(2, 3, 7, 8)])

##Potential problem with data: Looking at the "tails," I don't see any 0s or NAs. This means that, by 1870, all of the states and territories included in this dataset were using both water wheel and steam engine power. This seems a little hard to believe in some of the more remote and dry areas out west. 

##Here is another question and potential problem with the data: how are they measuring horsepower? What is the unit that one uses to measure horsepower? The data set and accompanying sheet aren't very helpful. This is a potential problem with this dataset, because we aren't sure what amount of power the waterwheel and steam engine power outputs are based on. A quick google reveals that there isn't a straightforward answer to how horsepower is measured. We would need to conduct research into 1870s measuring to geta better idea.

##One more problem: there is not information about what types of manufacturing were happening in each state. What was being made? This might be helpful to know. 

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Which states generated the most power by water wheel?
library(tidyverse)
manufacturing %>% 
  select(YEAR, STATE, water_wheel, steam_engine) %>% 
  arrange(desc(water_wheel))
 
```

```{r}
#Which states generated the most power by steam engine?

manufacturing %>% 
  select(YEAR, STATE, water_wheel, steam_engine) %>% 
  arrange(desc(steam_engine))
 
```

```{r}
#Based on the two tables above, it looks like the same five states produced the most power overall using both methods: New York, Pennsylvania, Massachusetts, Ohio, and Connecticut. This makes sense becuase the northeast was the early focal point of the Industrial Revolution in the US. It makes sense that there would be an abundance of water and steam power generated in those states, with midwestern states on major rivers or lakes in the bottom of the top ten power producers.

```

```{r}
#Which states produced the least of both kinds of power?
#How do we sort in ascending order? is there a command for this? 
#By using the sorting arrow function in the data spreadsheet that I imported, I can see that in cases of both water wheel and steam engine power, that the states that produced the least were, in ascending order: Dakota Territory, Arizona Territory, Idaho Territory. This makes sense, because these were less-developed frontier states in the western part of the country. 

```

```{r}
#Now I will start to visualize the data using ggplot. 

library(ggplot2)
ggplot(data = manufacturing) +
  geom_point(mapping = aes(x = water_wheel, y = steam_engine, color = STATE))

#This isn't very helpful. I will limit the states plotted to the top ten power producers.
```

```{r}
manufacturing_topten <- manufacturing %>% 
  filter(water_wheel > 52052424) %>% 
  filter(steam_engine > 18366780)

ggplot(manufacturing_topten, aes(x = water_wheel, y = steam_engine, color = STATE)) +
  geom_point()
 
#In this quick and dirty point plot, New York, Pennsylvania, and Massachusettes are shown as the top power producers. This isn't the best visualization, but at least it confirms what our earlier analysis says about the top power producing states. 

```
```{r}
#CONCLUSION: As I play with this data more, I see that it may not "tidy" enough for my purposes. I want to compare the two types of power generated within a state, and then compare THAT to other states, but these variables are in two columns in one table. I think I would need to combine the columns "water_wheel" and "steam_engine" into ONE column that was something like "power_generated". Then I would (hopefully) be able to create a histogram or bar graph using both variables. This would be my plan if I were going to continue working with this dataset further. 

```



